spring.application.name=SSU-2025-02_hemograma
# Configuração do DataSource (ajuste conforme seu banco)
spring.datasource.url=jdbc:mysql://localhost:3306/hemograma_db
spring.datasource.username=root
spring.datasource.password=sua_nova_senha_aqui

# Configuração do JPA/Hibernate
# O 'update' tentará criar a tabela se não existir
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect